
version: '3.9'

volumes:
  pg-db-data-dir:
  pg-db-schema-dir:


services:
  pg-database:
    image: 'kartoza/postgis:${TAG:-manual-build}'
    restart: 'always'
    # You can optionally mount to volume, to play with the persistence and
    # observe how the node will behave after restarts.
    volumes:
      - pg-db-data-dir:/var/lib/postgresql
      - ./tests:/tests
      - ../utils:/lib/utils
    environment:
      POSTGRES_DB: 'gis,data'
      POSTGRES_PASS: 'docker'
      ALL_DATABASES: TRUE
      SCHEMA_NAME: 'demo1,demo2'
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"

  pg-schema:
    image: 'kartoza/postgis:${TAG:-manual-build}'
    restart: 'always'
    # You can optionally mount to volume, to play with the persistence and
    # observe how the node will behave after restarts.
    volumes:
      - pg-db-schema-dir:/var/lib/postgresql
      - ./tests:/tests
      - ../utils:/lib/utils
    environment:
      POSTGRES_DB: 'gis,data'
      POSTGRES_PASS: 'docker'
      ALL_DATABASES: FALSE
      SCHEMA_NAME: 'demo1,demo2'
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"


